version: '3.4'

x-common-variables: &common-variables
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
  local-dev:
    container_name: local-dev 
    build:
      context: d7-docker
      dockerfile: webserver.Dockerfile
    environment:
      <<: *common-variables
      MYSQL_SERVER: local-dev-db
    ports:
      - "80:80"
      - "2222:22"
    depends_on:
      - "local-dev-db"
    extra_hosts: 
      - "demo-drupal.local:127.0.0.1"
    volumes:
      - ./src:/var/www/html/
    networks:
      default:
        aliases:
          - demo-drupal.local
       
  local-dev-db: 
    container_name: local-dev-db
    build: 
      context: d7-docker
      dockerfile: mysql.Dockerfile
    environment:
      <<: *common-variables
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./db-volumes
        target: /var/lib/mysql
        consistency: delegated
    networks:
      - default

  phpmyadmin:
    container_name: local-dev-pma
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: local-dev-db
    depends_on:
        - local-dev-db